name: Deploy on QA

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy_on_qa:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Create customer Env file
      working-directory: ./customer
      run: |
        touch .env
        echo APP_SECRET=jg_youtube_tutorial >> .env
        echo MONGODB_URI=mongodb://nosql-db:27017/shopping_ms_customer >> .env
        echo MESSAGE_BROKER_URL=amqps://qxspliae:udr0XJs3FpwWz2ChVPFXAWtqnXQe2e_I@rat.rmq2.cloudamqp.com/qxspliae >> .env
        echo EXCHANGE_NAME=ONLINE_STORE >> .env
        echo PORT=8001 >> .env
        cat .env

    - name: Create products Env file
      working-directory: ./products
      run: |
        touch .env
        echo APP_SECRET=jg_youtube_tutorial >> .env
        echo MONGODB_URI=mongodb://nosql-db:27017/shopping_ms_products >> .env
        echo MESSAGE_BROKER_URL=amqps://qxspliae:udr0XJs3FpwWz2ChVPFXAWtqnXQe2e_I@rat.rmq2.cloudamqp.com/qxspliae >> .env
        echo EXCHANGE_NAME=ONLINE_STORE >> .env
        echo PORT=8002 >> .env
        cat .env

    - name: Create shopping Env file
      working-directory: ./shopping
      run: |
        touch .env
        echo APP_SECRET=jg_youtube_tutorial >> .env
        echo MONGODB_URI=mongodb://nosql-db:27017/shopping_ms_shopping >> .env
        echo MESSAGE_BROKER_URL=amqps://qxspliae:udr0XJs3FpwWz2ChVPFXAWtqnXQe2e_I@rat.rmq2.cloudamqp.com/qxspliae >> .env
        echo EXCHANGE_NAME=ONLINE_STORE >> .env
        echo PORT=8003 >> .env
        cat .env

    - name: Generate deployment package
      run: |
        zip -r deploye.zip . -x '*.git'

    - name: Deploy on Elastic beanstalk QA Env
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: CD-ms
        environment_name: CD-ms-env
        version_label: "ver-${{ github.sha }}"
        region: eu-central-1
        deployment_package: deploye.zip
